### ISSUE TITLE
Allow secret tokens as credentials

### ISSUE THREAD

**Issue by shin-nien** [gardener/machine-controller-manager-provider-aws#106]
/area security
/kind enhancement
/priority 3

**What would you like to be added**:
The ability to not use [secretRef](https://github.com/gardener/machine-controller-manager-provider-aws/blob/2fd547ddb1c33c5d0c8733cb9182df80c7bef5ed/pkg/aws/apis/validation/validation.go#L182) and pass credentials to the AWS SDK via environment variables instead.

I believe that by making this field optional, the AWS SDK will fallback to looking for environment variables where we'd be able to set AWS_WEB_IDENTITY_TOKEN_FILE, AWS_ROLE_ARN etc.

**Why is this needed**:
An organisation's security policy may not allow the use of static AWS credentials for various reasons. An alternative to static credentials is to use short lived tokens issued by STS. [EKS does this using an OIDC provider and mutating webhook](https://github.com/aws/amazon-eks-pod-identity-webhook).

**Comment by himanshu-kun** [comment]
## Post grooming discussion

We think this is a nice to have feature, we can have a fallback mechanism where if the secret is not provided , then we use the environment variables.

**Comment by shin-nien** [comment]
>We think this is a nice to have feature, we can have a fallback mechanism where if the secret is not provided , then we use the environment variables.
> ...
> So if we understand your requirement correctly , the only thing missing is our support for ENV variables for credential secrets.

We think falling back to just environment variables could break the feature where you want different credentials for different machine classes.

Therefore we're thinking that `SecretRef` and `CredentialSecretRef` need to be able to support: `AWS_ROLE_ARN`, `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_STS_REGIONAL_ENDPOINTS` environment variables. This way each machine class can still have its own set of credentials if people want to do that.

We're still investigating but we're happy to raise a PR 👍

**Comment by himanshu-kun** [comment]
> We think falling back to just environment variables could break the feature where you want different credentials for different machine classes.

Yes that would also be the case. Only one set of env variables per pod could be set , as per the [aws doc for pod-identity-webhook](https://github.com/aws/amazon-eks-pod-identity-webhook) , so we would loose on the flexibility we have today.
> we're thinking that SecretRef and CredentialSecretRef need to be able to support: AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE and AWS_STS_REGIONAL_ENDPOINTS environment variables

I am curious if there is a way to achieve this using the pod-identity-webhook but as you said you are still investigating. Pls keep us posted with the solution you come up with.

**Comment by himanshu-kun** [comment]
Okay, then we'll only need some changes in `credentialSecretRef` secret and add support for the above said environment variables.
/title Allow secret tokens as credentials

**Comment by rishabh-11** [comment]
> Therefore we're thinking that SecretRef and CredentialSecretRef need to be able to support: AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE and AWS_STS_REGIONAL_ENDPOINTS environment variables. This way each machine class can still have its own set of credentials if people want to do that.

@shin-nien is this still needed? If not we would like to close the issue.
