### ISSUE TITLE
`GetMachineStatus` prevents machine deletion, if `SrcAndDstChecks` is disabled

### ISSUE THREAD

**Issue by hendrikKahl** [gardener/machine-controller-manager-provider-aws#165]
**What happened**:

We saw a machine stuck in status `Terminating`  with 

```
Error occurred with decoding machine error status while getting VM status, aborting without retry. machine code: machine codes error: code = [Uninitialized] message = [VM "i-<id>" associated with machine "<name>" has SourceDestCheck=true despite providerSpec.SrcAndDstChecksEnabled=false] Set machine status to termination. Now, getting VM Status
```

From the machine creation logs we could derive that https://github.com/gardener/machine-controller-manager-provider-aws/blob/9e7ed79f263505aca9dcc865af3b60a131bc4f69/pkg/aws/core_util.go#L65-L80 never ran successfully for this machine. 

With `GetMachineStatus` being called also upon [deletion of a machine](https://github.com/gardener/machine-controller-manager/blob/2c1c4e4538dc93a4f590446ff0c427903b6d59da/pkg/util/provider/machinecontroller/machine.go#L656-L663), the status is stuck and requires manual intervention (e.g. patching the instance's attribute).

**What you expected to happen**:

`GetMachineStatus` should not block machine deletion.

**How to reproduce it (as minimally and precisely as possible)**:
- create a machine with provider AWS
- patch the instance status `aws ec2 modify-instance-attribute --no-source-dest-check --instance-id i-<id>`
- trigger the deletion of the machine

**Anything else we need to know**:

**Environment**:

**Comment by rishabh-11** [comment]
https://github.com/gardener/machine-controller-manager/pull/928 is merged and the corresponding version of MCM is also updated in the provider.

/close
