### ISSUE TITLE
Support to provision dedicated host at AWS

### ISSUE THREAD

**Issue by renkes** [gardener/machine-controller-manager-provider-aws#24]
We have the need to start instances on dedicated hosts at AWS. Some of the huge memory instances like u-6tb1.metal are only available through dedicated hosts which are exclusively assigned into a customers account at AWS.

To create instances on these dedicated host, the AWS ec run-instance command needs to support the placement parameter.

Example command:
aws ec2 run-instances --image-id ami-xxxx --instance-type u-6tb1.metal --placement Affinity=host,Tenancy=host,AvailabilityZone=eu-central-1b --security-group-ids sg-abcd --subnet-id subnet-xyz --region eu-central-1

**Comment by prashanth26** [comment]
We had a short discussion internally. One idea to implement this was to provide an annotation on shoot/worker-pool to allow setting of these flags - `--placement Affinity=host,Tenancy=host,AvailabilityZone=eu-central-1b` based on this annotation. 

However, this is still under discussion. We will pick this issue up once we are done with our current set of tasks.

**Comment by prashanth26** [comment]
Some reference links
- https://aws.amazon.com/ec2/instance-types/high-memory/
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html
