### ISSUE TITLE
Failing to delete machine which instance id is not found in the infrastruture

### ISSUE THREAD

**Issue by vpnachev** [gardener/machine-controller-manager-provider-aws#56]
**What happened**:
A shoot cluster has been set in deletion, but it fails with
```
Flow "Shoot cluster deletion" encountered task errors: [task "Waiting until shoot worker nodes have been terminated" failed: Failed to delete Worker shoot--foo--bar/bar: Error deleting worker: Failed while waiting for all machine resources to be deleted: 'machine shoot--foo--bar-aws-r5d-large-z1-57655-wzp5n failed: VM deletion failed due to - machine codes error: code = [Internal] message = [InvalidInstanceID.NotFound: The instance ID 'i-0c2f23c5d881ca0f6' does not exist
	status code: 400, request id: 553fa61f-35a5-4fd2-ad1e-15d30dd2cc10]. Aborting operation. Initiate VM deletion']
```

There is indeed no such instance in AWS
``` bash
$ aws ec2 describe-instances --instance-ids i-0c2f23c5d881ca0f6 --output json
{
    "Reservations": []
}
```

The error originates from the respective machine
```bash
$ k get machine shoot--foo--bar-aws-r5d-large-z1-57655-wzp5n -o json | jq  .status.lastOperation.description -cr
VM deletion failed due to - machine codes error: code = [Internal] message = [InvalidInstanceID.NotFound: The instance ID 'i-0c2f23c5d881ca0f6' does not exist
        status code: 400, request id: c5e98927-903b-4f61-83d8-b2c852c75c68]. Aborting operation. Initiate VM deletion
```

From this point of view, it looks like this VM does not exist anymore in the infrastructure.

**What you expected to happen**:
The machine object to be deleted when the respective VM no longer exist on the infrastructure.

**How to reproduce it (as minimally and precisely as possible)**:
N/A
**Anything else we need to know**:

**Environment**:
AWS

**Comment by himanshu-kun** [comment]
On first looks , I see that we do have a [logic](https://github.com/gardener/machine-controller-manager/blob/cc66a5130b21528e8b3c0ef3301de318efa5807c/pkg/util/provider/machinecontroller/machine_util.go#L1150-L1153) for this kind of scenario, but its just that the error code in this case turns out to be `Internal` and not `NotFound` so the logic doesn't kick in.
Will take another look
